(()=>{'use strict';const trashFiles=[["회의록_수정본.txt","txt","회의 취소됨\n사유: 한소율 연구소장 / 시뮬용 병원체 유출로 인한 컨디션 악화\n\n비고: 소장님께서는 단순 피로라고 정정 요청하셨음.\n회의실과 화장실 사이를 오가신 횟수는 회의록에서 삭제할 것."],["SCAT_update.log","log","업데이트 확인 완료. 새 업데이트가 없습니다."],["비품신청_반려.xls","xls","신청 품목: 스팀밀크 커피머신\n처리 결과: 반려\n사유: 한소율 연구소장의 유당 불내증으로 인한 사내 우유 관련 제품 반입 금지\n\n재신청 의견: 소장님만 안 드시면 되는 것 아닌가요?\n결재자 의견: 반려. 사유 다시 읽어."],["인수인계_구버전.txt","txt","소장실 지원 업무 인수인계\n\n1. 회의는 가급적 30분 이내로 잡을 것.\n2. 소장님이 급히 자리를 비우시면 \"외부 통화 중\"으로 안내할 것.\n3. 외부 통화가 왜 늘 같은 복도 끝에서 이루어지는지는 묻지 말 것.\n4. 복귀하신 직후에는 진행 상황만 보고할 것. 안부 질문 금지."],["desktop.ini","ini","이 폴더의 보기 설정은 더 이상 사용하지 않습니다."],["scan_0047.dat","dat","evidence"],["점심메뉴.txt","txt","수요일 메뉴 수정 요청\n요청자: 한소율 연구소장\n\n크림수프 → 맑은 수프\n크림파스타 → 오일파스타\n우유 푸딩 → 제공 취소\n\n영양사 의견: 지난번에는 괜찮다고 하셨는데요.\n소장실 답변: 지난번 오후 일정이 전부 취소된 이유를 다시 설명해야 하나요?"],["프린터_테스트.txt","txt","ABCDEFGHIJKLMNOPQRSTUVWXYZ\n0123456789\n인쇄 테스트 완료"],["~plan_backup.tmp","tmp","복구 가능한 내용이 없습니다."],["신청서_빈양식.doc","doc","성명: __________\n부서: __________\n신청 내용: __________"],["연락망_old.csv","csv","이 연락망은 만료되었습니다."],["정산_복사본.xls","xls","법인카드 정산 보완 요청\n항목: 소장실 전용 무유당 음료\n\n구매 사유: 업무 연속성 확보\n회계팀 문의: 일반 음료와 업무 연속성이 무슨 관계인가요?\n소장실 답변: 지난달 회의 중단 시간을 확인하세요."],["readme.bak","bak","파일 정리 후 삭제할 것."],["예약_취소.txt","txt","예약 취소 안내\n예약자: 한소율\n장소: 3층 대회의실\n변경 요청: 화장실에서 가장 가까운 회의실로 변경\n\n시설팀 답변: 해당 위치에는 회의실이 없습니다.\n예약자 답변: 그럼 오늘 회의는 서면으로 해."],["cache_019.tmp","tmp","캐시가 비어 있습니다."]];const dialog=document.createElement('dialog');dialog.id='trash-dialog';
 dialog.innerHTML=`<div class="trash-title"><strong id="trash-title">휴지통</strong><button id="trash-close" aria-label="닫기">×</button></div><div id="trash-content"><div class="trash-toolbar">휴지통 <span>삭제된 파일 ${trashFiles.length}개</span></div><div class="trash-grid">${trashFiles.map(([name,type],i)=>`<button type="button" class="trash-file" data-trash-index="${i}" aria-label="${name}"><span class="file-glyph file-${type}" aria-hidden="true"><span>${type.toUpperCase()}</span></span><span class="trash-filename">${name}</span></button>`).join('')}</div><div id="trash-preview" hidden><strong id="trash-preview-name"></strong><pre id="trash-preview-body"></pre></div><p class="trash-status" id="trash-status">파일을 더블클릭하여 엽니다.</p></div>`;

document.body.append(dialog);const q=s=>dialog.querySelector(s);
 document.addEventListener('click',e=>{if(e.target.closest('[data-action="trash"]')){q('#trash-title').textContent='휴지통';dialog.classList.add('trash-window');q('#trash-preview').hidden=true;q('#trash-status').textContent=(window.matchMedia('(pointer: coarse)').matches?'파일을 눌러 엽니다.':'파일을 더블클릭하여 엽니다.');q('#trash-content').hidden=false;dialog.showModal();}});
 // Editor keys must not trigger the game's keyboard shortcuts.
 dialog.addEventListener('keydown',e=>e.stopPropagation());
 function openTrashFile(index){const file=trashFiles[index];if(!file)return;const [name,,content]=file;if(content==='evidence'){dialog.close();act('director-evidence');return;}q('#trash-preview').hidden=false;q('#trash-preview-name').textContent=name;q('#trash-preview-body').textContent=content;q('#trash-status').textContent=name+' · 내용 보기';}
 q('#trash-content').addEventListener('click',e=>{const item=e.target.closest('[data-trash-index]');if(!item)return;for(const el of dialog.querySelectorAll('.trash-file'))el.classList.toggle('selected',el===item);q('#trash-status').textContent=trashFiles[Number(item.dataset.trashIndex)][0];if(window.matchMedia('(pointer: coarse)').matches)openTrashFile(Number(item.dataset.trashIndex));});
 q('#trash-content').addEventListener('dblclick',e=>{const item=e.target.closest('[data-trash-index]');if(item)openTrashFile(Number(item.dataset.trashIndex));});
 q('#trash-content').addEventListener('keydown',e=>{if(e.key==='Enter'){const item=e.target.closest('[data-trash-index]');if(item){e.preventDefault();openTrashFile(Number(item.dataset.trashIndex));}}});

q('#trash-close').onclick=()=>dialog.close();})();